version: '3.8'

services:
  # ------------------------------------------------------------------
  # Servidor Minecraft Mohist 1.20.1
  # ------------------------------------------------------------------
  mohist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mohist
    volumes:
      - mc-server:/server          # persistencia de todo el server
    environment:
      EULA: "TRUE"
    networks:
      coolify:
        aliases:
          - minecraft             # Alias para usar un nombre corto
    restart: unless-stopped
    ports:
      - "25565:25565"   # Minecraft
      - "25575:25575"   # RCON                # Solo visible dentro de la red coolify

  # ------------------------------------------------------------------
  # Playit Agent
  # ------------------------------------------------------------------
  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit-agent
    restart: unless-stopped
    networks:
      - coolify
    volumes:
      - ./playit.yml:/playit.yml
    environment:
      SECRET_KEY: "d0c343546f5d0a89d494c43aea0fd9b982ae97cf4ff8cfd0e54fe9e47b8ac95d"
    command: ["playit", "--config", "/playit.yml"]

# ------------------------------------------------------------------
# Volumen persistente del servidor Minecraft
# ------------------------------------------------------------------
volumes:
  mc-server:

# ------------------------------------------------------------------
# Red externa administrada por Coolify
# ------------------------------------------------------------------
networks:
  coolify:
    external: true
    name: coolify
