# @format

version: "3.8"

services:
  # ------------------------------------------------------------------
  #  Cloudflare Tunnel (TCP) para mc.theoasiss.us
  # ------------------------------------------------------------------
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: mc-tunnel
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel --config /etc/cloudflared/config.yml run --token ${TUNNEL_TOKEN}
    volumes:
      - ./config/ingress.yaml:/etc/cloudflared/config.yml:ro
    networks:
      - coolify

  # ------------------------------------------------------------------
  #  Servidor Minecraft Mohist 1.20.1
  # ------------------------------------------------------------------
  mohist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-mohist-1201
    volumes:
      - mc-server:/server # /server completo persistente
    environment:
      EULA: "TRUE"
    networks:
      - coolify
    restart: unless-stopped
    expose:
      - "25565" # solo visible dentro de la red coolify

  # ------------------------------------------------------------------
  #  HAProxy - Proxy TCP para Minecraft
  # ------------------------------------------------------------------
  haproxy:
    image: haproxy:alpine
    container_name: minecraft-haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - coolify
    depends_on:
      - mohist
    restart: unless-stopped
    ports:
      - "25565:25565" # expone el proxy hacia fuera

# ------------------------------------------------------------------
#  Volumen persistente (todo /server)
# ------------------------------------------------------------------
volumes:
  mc-server:

# ------------------------------------------------------------------
#  Red externa que gestiona Coolify
# ------------------------------------------------------------------
networks:
  coolify:
    external: true
    name: coolify
