version: '3.8'

services:
  mohist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-mohist-1201
    volumes:
      - mc-server:/server          # ← TODA la carpeta /server persistente
    environment:
      EULA: "TRUE"
    networks:
      - coolify
    restart: unless-stopped

volumes:
  mc-server:                       # volumen nombrado

networks:
  coolify:
    external: true
    name: coolify