# @format

version: "3.8"

services:
  # ------------------------------------------------------------------
  # Servidor Minecraft Mohist 1.20.1
  # ------------------------------------------------------------------
  mohist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-mohist-1201
    volumes:
      - mc-server:/server
    environment:
      EULA: "TRUE"
    restart: unless-stopped
    networks:
      - coolify
    expose:
      - "25565" # Solo dentro de la red Docker

  # ------------------------------------------------------------------
  # Playit Tunnel
  # ------------------------------------------------------------------
  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit-agent
    restart: unless-stopped
    networks:
      - coolify
    volumes:
      - ./playit.yml:/playit.yml
    environment:
      SECRET_KEY: "d0c343546f5d0a89d494c43aea0fd9b982ae97cf4ff8cfd0e54fe9e47b8ac95d"
    command: ["playit", "--config", "/playit.yml"]

# ------------------------------------------------------------------
# Volumen persistente para Minecraft
# ------------------------------------------------------------------
volumes:
  mc-server:

# ------------------------------------------------------------------
# Red externa gestionada por Coolify
# ------------------------------------------------------------------
networks:
  coolify:
    external: true
    name: coolify
